# Updated: removed duplicate report generation step

#!/bin/bash

set -e

echo "[1] Starting ZAP daemon..."

docker rm -f zap-daemon 2>/dev/null || true

docker run -d \
  --name zap-daemon \
  --network host \
  --memory=2g \
  --shm-size=1g \
  ghcr.io/zaproxy/zaproxy:stable \
  zap.sh -daemon -host 127.0.0.1 -port 8090 -config api.disablekey=true

echo "[2] Waiting for ZAP API..."

for i in {1..60}; do
  if curl -s http://127.0.0.1:8090 >/dev/null; then
    echo "[OK] ZAP is ready"
    break
  fi
  echo "  Not ready yet ($i/60)"
  sleep 5
done

echo "[3] Activating Python venv"
source zap-env/bin/activate

echo "[4] Running Baseline Scan"
./scripts/run-baseline.sh

echo "[5] Running Full Scan"
./scripts/run-full-scan.sh

echo "[6] Generating Reports"
./scripts/generate-report.sh

#echo "[7] Completed. Reports located in scans/reports/"
echo "[6] Reports already generated by full scan"
echo "Reports → scans/reports/"

# Optional cleanup
# docker stop zap-daemon
